[[manager.prepend_keymap]]
on   = [ "<C-s>" ]
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = [ "l" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = [ "p" ]
run  = "plugin --sync smart-paste"
desc = "Paste into the hovered directory or CWD"

[[manager.prepend_keymap]]
on  = [ "k" ]
run = "plugin --sync arrow --args=-1"

[[manager.prepend_keymap]]
on  = [ "j" ]
run = "plugin --sync arrow --args=1"

[[manager.prepend_keymap]]
on   = [ "J" ]
run  = "plugin keyjump"
desc = "Keyjump (Normal mode)"

[[manager.prepend_keymap]]
on   = [ "<F1>"]
run  = "help"
desc = "Help"
