name: Test dotfiles deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkokut code
        uses: actions/checkout@v3

      - name: Set up Podman
        run: sudo apt-get update && sudo apt-get install -y podman

      - name: Build test container
        env:
          REPO_PATH: ${{ github.workspace }}
        run: ./util/build_test_container.sh

      - name: Setup & validate environment
        run: podman run --rm --entrypoint /bin/sh dotfiles-test -c "./setup.sh && ./validate_environment.sh"
